// Bundled sample data so the prototype runs with zero backend setup.
// Demo sign-in personas (see /login):
//   ailsa@demo    — Quiet Seeker, East Lothian brief, 99% match waiting
//   gordon@demo   — Hush Home seller (live listing in Gullane)
//   rachel@demo   — both roles: selling in Shawlands, seeking in East Lothian
//   struan@demo   — seller mid-flow: draft listing, Home Report gate not passed
//   phil@demo     — admin (full back-office)

import type {
  AppNotification,
  HushHome,
  Introduction,
  Invoice,
  Lawyer,
  Offer,
  SavedHome,
  SeekerBrief,
  User,
  Viewing,
  ViewingSlot,
} from "./types";

export const sampleUsers: User[] = [
  { id: "u-phil", email: "phil@demo.matchlisted.com", name: "Phil Mowat", isAdmin: true, createdAt: "2026-06-01T09:00:00Z" },
  { id: "u-ailsa", email: "ailsa@demo.matchlisted.com", name: "Ailsa Drummond", createdAt: "2026-06-20T10:00:00Z" },
  { id: "u-gordon", email: "gordon@demo.matchlisted.com", name: "Gordon Baird", createdAt: "2026-06-12T10:00:00Z" },
  { id: "u-rachel", email: "rachel@demo.matchlisted.com", name: "Rachel Tennant", createdAt: "2026-06-15T10:00:00Z" },
  { id: "u-struan", email: "struan@demo.matchlisted.com", name: "Struan Kerr", createdAt: "2026-07-10T10:00:00Z" },
  { id: "u-morag", email: "morag@demo.matchlisted.com", name: "Morag Sinclair", createdAt: "2026-06-05T10:00:00Z" },
  { id: "u-ewan", email: "ewan@demo.matchlisted.com", name: "Ewan MacRae", createdAt: "2026-06-08T10:00:00Z" },
  { id: "u-isla", email: "isla@demo.matchlisted.com", name: "Isla Farquhar", createdAt: "2026-06-18T10:00:00Z" },
  { id: "u-callum", email: "callum@demo.matchlisted.com", name: "Callum Boyd", createdAt: "2026-06-22T10:00:00Z" },
  { id: "u-niamh", email: "niamh@demo.matchlisted.com", name: "Niamh Docherty", createdAt: "2026-06-25T10:00:00Z" },
  { id: "u-dougie", email: "dougie@demo.matchlisted.com", name: "Dougie Lennox", createdAt: "2026-06-26T10:00:00Z" },
  { id: "u-freya", email: "freya@demo.matchlisted.com", name: "Freya Cunningham", createdAt: "2026-06-28T10:00:00Z" },
  { id: "u-hamish", email: "hamish@demo.matchlisted.com", name: "Hamish Grant", createdAt: "2026-07-01T10:00:00Z" },
  { id: "u-elspeth", email: "elspeth@demo.matchlisted.com", name: "Elspeth Wallace", createdAt: "2026-07-03T10:00:00Z" },
  { id: "u-kirsty", email: "kirsty@demo.matchlisted.com", name: "Kirsty Muir", createdAt: "2026-06-10T10:00:00Z" },
  { id: "u-sandy", email: "sandy@demo.matchlisted.com", name: "Sandy Lindsay", createdAt: "2026-07-14T10:00:00Z" },
  { id: "u-tam", email: "tam@demo.matchlisted.com", name: "Tam Buchanan", createdAt: "2026-07-20T10:00:00Z" },
  { id: "u-mowatt", email: "clients@demo.matchlisted.com", name: "Mowatt Client", createdAt: "2026-07-01T09:00:00Z" },
  { id: "u-fenella", email: "fenella@demo.matchlisted.com", name: "Fenella Ross", createdAt: "2026-05-20T10:00:00Z" },
];

const sig = (typedName: string, signedAt: string, version: string) => ({
  typedName,
  signedAt,
  ip: "demo",
  version,
});

export const sampleBriefs: SeekerBrief[] = [
  {
    userId: "u-ailsa",
    publicRef: "QS-2104",
    headline: "Golf-mad family chasing the coast",
    story:
      "We've holidayed on this stretch of coast for fifteen years and the clubs are already in the boot. We're cash buyers with nothing to sell, so if the right detached family home comes up near the links, we can move as fast as the seller wants.",
    areas: ["east-lothian/gullane", "east-lothian/north-berwick", "east-lothian/aberlady"],
    budgetMin: 600000,
    budgetMax: 900000,
    minBeds: 4,
    minBaths: 2,
    garden: "must-have",
    types: ["detached", "cottage"],
    features: ["parking", "sea-views", "garage"],
    position: "cash-nothing-to-sell",
    notes: "Golf on the doorstep would be the dream.",
    contract: sig("Ailsa Drummond", "2026-06-20T10:05:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-06-20T10:05:00Z",
    updatedAt: "2026-06-20T10:05:00Z",
  },
  {
    userId: "u-rachel",
    publicRef: "QS-2118",
    headline: "Trading the city for market-town life",
    story:
      "Selling our city flat and swapping it for somewhere with a bit of history: a cottage or period terrace within walking distance of a good butcher and a better pub. Mortgage agreed in principle; our own sale is under way.",
    areas: ["east-lothian/haddington", "east-lothian/east-linton", "east-lothian/gifford"],
    budgetMin: 350000,
    budgetMax: 500000,
    minBeds: 3,
    minBaths: 1,
    garden: "nice-to-have",
    types: ["cottage", "semi-detached", "terraced"],
    features: ["period-features"],
    position: "mortgage-to-sell",
    contract: sig("Rachel Tennant", "2026-06-15T10:20:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-06-15T10:20:00Z",
    updatedAt: "2026-07-02T09:00:00Z",
  },
  {
    userId: "u-callum",
    publicRef: "QS-2131",
    headline: "First-timer hunting an honest tenement",
    story:
      "First-time buyer, deposit saved, mortgage in principle sorted. I want a proper red-sandstone flat with cornicing and a bay window, southside or west end, and I'm not scared of a kitchen that needs doing.",
    areas: ["glasgow/west-end", "glasgow/shawlands", "east-renfrewshire/giffnock"],
    budgetMin: 200000,
    budgetMax: 280000,
    minBeds: 2,
    minBaths: 1,
    garden: "no-preference",
    types: ["flat"],
    features: ["period-features"],
    position: "first-time-buyer",
    contract: sig("Callum Boyd", "2026-06-22T11:00:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-06-22T11:00:00Z",
    updatedAt: "2026-06-22T11:00:00Z",
  },
  {
    userId: "u-niamh",
    publicRef: "QS-2146",
    headline: "Downsizing to a sea view",
    story:
      "The family house is sold and I'm down to the fun part: a flat where I can see the water from the kitchen table. Cash in the bank once my sale completes. A view of Cumbrae would seal it.",
    areas: ["north-ayrshire/largs", "north-ayrshire/west-kilbride", "north-ayrshire/millport"],
    budgetMin: 200000,
    budgetMax: 380000,
    minBeds: 2,
    minBaths: 1,
    garden: "no-preference",
    types: ["flat"],
    features: ["sea-views"],
    position: "cash-after-sale",
    notes: "A flat in Largs with a view of Cumbrae.",
    contract: sig("Niamh Docherty", "2026-06-25T09:30:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-06-25T09:30:00Z",
    updatedAt: "2026-06-25T09:30:00Z",
  },
  {
    userId: "u-dougie",
    publicRef: "QS-2152",
    headline: "East Neuk family, sold and ready",
    story:
      "House sold, mortgage agreed, kids enrolled for August. We just need the house now. Four beds, a garden worth the name, and space for two desks. St Andrews to Anstruther, we know every harbour wall already.",
    areas: ["fife/st-andrews", "fife/elie", "fife/anstruther"],
    budgetMin: 500000,
    budgetMax: 750000,
    minBeds: 4,
    minBaths: 2,
    garden: "must-have",
    types: ["detached"],
    features: ["garage", "home-office"],
    position: "mortgage-sold",
    contract: sig("Dougie Lennox", "2026-06-26T14:00:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-06-26T14:00:00Z",
    updatedAt: "2026-06-26T14:00:00Z",
  },
  {
    userId: "u-freya",
    publicRef: "QS-2167",
    headline: "Stockbridge dreamer with a sale agreed",
    story:
      "I've rented in Stockbridge for six years and I'm not leaving the postcode without a fight. Sale agreed on my old place, mortgage offer in hand, looking for a period flat with light, cornicing and somewhere to put a piano.",
    areas: ["edinburgh/stockbridge", "edinburgh/new-town", "edinburgh/marchmont"],
    budgetMin: 400000,
    budgetMax: 520000,
    minBeds: 2,
    minBaths: 1,
    garden: "nice-to-have",
    types: ["flat"],
    features: ["period-features"],
    position: "mortgage-to-sell",
    contract: sig("Freya Cunningham", "2026-06-28T16:00:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-06-28T16:00:00Z",
    updatedAt: "2026-06-28T16:00:00Z",
  },
  {
    userId: "u-hamish",
    publicRef: "QS-2173",
    headline: "Highland first-timer, new-build keen",
    story:
      "Moving back north for work after a decade away. First-time buyer with the mortgage agreed, after somewhere warm, low-maintenance and new enough that the weekends stay mine. Inverness or Nairn, either suits.",
    areas: ["highland/inverness", "highland/nairn"],
    budgetMin: 250000,
    budgetMax: 330000,
    minBeds: 3,
    minBaths: 2,
    garden: "nice-to-have",
    types: ["townhouse", "semi-detached"],
    features: ["new-build", "parking"],
    position: "first-time-buyer",
    contract: sig("Hamish Grant", "2026-07-01T12:00:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-07-01T12:00:00Z",
    updatedAt: "2026-07-01T12:00:00Z",
  },
  {
    userId: "u-elspeth",
    publicRef: "QS-2189",
    headline: "Writer wanting hills out the window",
    story:
      "I work from home and the home can be anywhere, so it may as well be somewhere beautiful. A stone cottage with a real garden, hills from the desk window, and a village with one good coffee shop. Cash once my sale concludes.",
    areas: ["perth-kinross/dunkeld", "perth-kinross/pitlochry", "stirling/callander"],
    budgetMin: 300000,
    budgetMax: 420000,
    minBeds: 2,
    minBaths: 1,
    garden: "must-have",
    types: ["cottage"],
    features: ["rural"],
    position: "cash-after-sale",
    contract: sig("Elspeth Wallace", "2026-07-03T10:00:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-07-03T10:00:00Z",
    updatedAt: "2026-07-03T10:00:00Z",
  },
  {
    userId: "u-kirsty",
    publicRef: "QS-2095",
    headline: "Ayrshire coast, bungalow preferred",
    story:
      "Sold, packed, and staying with family until we find it, so we're genuinely ready. A bungalow or easy semi near the front at Troon or Prestwick, with a garage for the golf trolleys and the grandkids' bikes.",
    areas: ["south-ayrshire/troon", "south-ayrshire/prestwick"],
    budgetMin: 300000,
    budgetMax: 360000,
    minBeds: 3,
    minBaths: 2,
    garden: "nice-to-have",
    types: ["bungalow", "semi-detached"],
    features: ["parking", "garage"],
    position: "mortgage-sold",
    contract: sig("Kirsty Muir", "2026-06-10T09:00:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-06-10T09:00:00Z",
    updatedAt: "2026-06-10T09:00:00Z",
  },
  {
    userId: "u-fenella",
    publicRef: "QS-2061",
    headline: "Borders cottage hunter, cash ready",
    story:
      "Retired early, sold up, and now renting in Melrose while I look, which means no chain, no mortgage, no drama. A stone cottage with a proper garden and period bones; I'll happily take on a project for the right spot.",
    areas: ["scottish-borders/melrose", "scottish-borders/peebles"],
    budgetMin: 350000,
    budgetMax: 450000,
    minBeds: 3,
    minBaths: 1,
    garden: "must-have",
    types: ["cottage", "detached"],
    features: ["rural", "period-features"],
    position: "cash-nothing-to-sell",
    contract: sig("Fenella Ross", "2026-05-20T10:30:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-05-20T10:30:00Z",
    updatedAt: "2026-05-20T10:30:00Z",
  },
  {
    userId: "u-sandy",
    publicRef: "QS-2210",
    headline: "Cash buyer, wide brief, East Lothian coast",
    story:
      "We're cash buyers with a deliberately wide brief: the right house matters far more to us than the number on it. Anything from a village bungalow to a substantial family home between Longniddry and North Berwick. If it feels right, we can conclude quickly and quietly.",
    areas: [
      "east-lothian/north-berwick",
      "east-lothian/gullane",
      "east-lothian/aberlady",
      "east-lothian/longniddry",
    ],
    budgetMin: 200000,
    budgetMax: 800000,
    minBeds: 2,
    minBaths: 1,
    garden: "nice-to-have",
    types: ["detached", "semi-detached", "bungalow", "cottage"],
    features: ["parking"],
    position: "cash-nothing-to-sell",
    notes: "Flexible on everything except the coastline.",
    contract: sig("Sandy Lindsay", "2026-07-14T10:10:00Z", "seeker-v1.0-2026-07"),
    createdAt: "2026-07-14T10:10:00Z",
    updatedAt: "2026-07-14T10:10:00Z",
  },
];

// One introduction mid-pipeline for the demo: Struan saw Ailsa's public
// profile and clicked "they might want my home". His Morningside listing is
// still draft (no verified Home Report), so the admin gate is not yet met.
export const sampleIntroductions: Introduction[] = [
  {
    id: "intro-1",
    seekerId: "u-ailsa",
    sellerId: "u-struan",
    homeId: "h-morningside",
    status: "new",
    createdAt: "2026-07-12T09:40:00Z",
  },
];

export const sampleHomes: HushHome[] = [
  {
    id: "h-gullane",
    sellerId: "u-gordon",
    headline: "Golf-view Edwardian villa beside the links",
    areaId: "east-lothian/gullane",
    addressLine: "14 Marine Terrace, Gullane",
    price: 875000,
    beds: 4,
    baths: 3,
    type: "detached",
    garden: true,
    features: ["parking", "period-features", "sea-views"],
    description:
      "A handsome Edwardian villa a short walk from Gullane No. 1, with sea glimpses over the Forth, a south-facing garden and beautifully kept period detail throughout.",
    photos: ["/photos/gullane-villa.jpg"],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "allied-surveyors",
      orderedAt: "2026-06-13T09:00:00Z",
      invoiceId: "inv-hr-gullane",
      fileName: "home-report-14-marine-terrace.pdf",
      uploadedAt: "2026-06-19T09:00:00Z",
      verifiedAt: "2026-06-19T15:00:00Z",
    },
    contract: sig("Gordon Baird", "2026-06-12T10:30:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-06-12T10:30:00Z",
  },
  {
    id: "h-shawlands",
    sellerId: "u-rachel",
    headline: "Bay-windowed tenement flat by Queen's Park",
    areaId: "glasgow/shawlands",
    addressLine: "2/1, 48 Kilmarnock Road, Shawlands",
    price: 265000,
    beds: 2,
    baths: 1,
    type: "flat",
    garden: false,
    features: ["period-features"],
    description:
      "A classic red-sandstone tenement flat with original cornicing, a sweeping bay window and Queen's Park at the end of the street.",
    photos: ["/photos/shawlands-tenement.jpg"],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "graham-sibbald",
      orderedAt: "2026-06-16T09:00:00Z",
      invoiceId: "inv-hr-shawlands",
      fileName: "home-report-48-kilmarnock-road.pdf",
      uploadedAt: "2026-06-22T09:00:00Z",
      verifiedAt: "2026-06-22T13:00:00Z",
    },
    contract: sig("Rachel Tennant", "2026-06-15T10:40:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-06-15T10:40:00Z",
  },
  {
    id: "h-largs",
    sellerId: "u-morag",
    headline: "Seafront flat looking over to Cumbrae",
    areaId: "north-ayrshire/largs",
    addressLine: "5 Broomfields Promenade, Largs",
    price: 295000,
    beds: 3,
    baths: 2,
    type: "flat",
    garden: false,
    features: ["sea-views", "parking"],
    description:
      "Front-line promenade living: three bedrooms, two bathrooms and an unbroken view across the Firth of Clyde to Great Cumbrae.",
    photos: ["/photos/largs-seafront.jpg"],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "allied-surveyors",
      orderedAt: "2026-06-06T09:00:00Z",
      invoiceId: "inv-hr-largs",
      fileName: "home-report-5-broomfields.pdf",
      uploadedAt: "2026-06-12T09:00:00Z",
      verifiedAt: "2026-06-12T12:00:00Z",
    },
    contract: sig("Morag Sinclair", "2026-06-05T11:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-06-05T11:00:00Z",
  },
  {
    id: "h-stockbridge",
    sellerId: "u-ewan",
    headline: "Georgian garden flat by the Water of Leith",
    areaId: "edinburgh/stockbridge",
    addressLine: "7A Dean Terrace, Stockbridge",
    price: 495000,
    beds: 2,
    baths: 2,
    type: "flat",
    garden: true,
    features: ["period-features"],
    description:
      "A rare Georgian garden flat with its own front door, working shutters, and a private walled garden two minutes from the Sunday market.",
    photos: [],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "graham-sibbald",
      orderedAt: "2026-06-09T09:00:00Z",
      invoiceId: "inv-hr-stockbridge",
      fileName: "home-report-7a-dean-terrace.pdf",
      uploadedAt: "2026-06-15T09:00:00Z",
      verifiedAt: "2026-06-15T16:00:00Z",
    },
    contract: sig("Ewan MacRae", "2026-06-08T10:15:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-06-08T10:15:00Z",
  },
  {
    id: "h-standrews",
    sellerId: "u-morag",
    headline: "Family home a nine-iron from the Old Course",
    areaId: "fife/st-andrews",
    addressLine: "3 Gibson Place, St Andrews",
    price: 725000,
    beds: 5,
    baths: 3,
    type: "detached",
    garden: true,
    features: ["garage", "home-office"],
    description:
      "Five bedrooms, a mature garden, a proper study, and the West Sands within earshot. Term-time lets have never touched it.",
    photos: [],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "allied-surveyors",
      orderedAt: "2026-06-20T09:00:00Z",
      invoiceId: "inv-hr-standrews",
      fileName: "home-report-3-gibson-place.pdf",
      uploadedAt: "2026-06-26T09:00:00Z",
      verifiedAt: "2026-06-26T11:00:00Z",
    },
    contract: sig("Morag Sinclair", "2026-06-19T09:45:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-06-19T09:45:00Z",
  },
  {
    id: "h-dunkeld",
    sellerId: "u-isla",
    headline: "Riverside cottage under the larches",
    areaId: "perth-kinross/dunkeld",
    addressLine: "Larch Cottage, Inver, by Dunkeld",
    price: 385000,
    beds: 3,
    baths: 1,
    type: "cottage",
    garden: true,
    features: ["rural", "parking"],
    description:
      "A whitewashed stone cottage above the Braan with a wild-ish garden, a wood-burner that does the heavy lifting, and red squirrels for neighbours.",
    photos: [],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "graham-sibbald",
      orderedAt: "2026-06-21T09:00:00Z",
      invoiceId: "inv-hr-dunkeld",
      fileName: "home-report-larch-cottage.pdf",
      uploadedAt: "2026-06-27T09:00:00Z",
      verifiedAt: "2026-06-27T10:30:00Z",
    },
    contract: sig("Isla Farquhar", "2026-06-20T14:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-06-20T14:00:00Z",
  },
  {
    id: "h-troon",
    sellerId: "u-ewan",
    headline: "Bright bungalow near the beach",
    areaId: "south-ayrshire/troon",
    addressLine: "22 Bentinck Drive, Troon",
    price: 340000,
    beds: 3,
    baths: 2,
    type: "bungalow",
    garden: true,
    features: ["parking", "garage"],
    description:
      "A light, level-access bungalow ten minutes' walk from the South Beach, with a garage, a sunroom and not a single step to trip on.",
    photos: [],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "allied-surveyors",
      orderedAt: "2026-06-11T09:00:00Z",
      invoiceId: "inv-hr-troon",
      fileName: "home-report-22-bentinck-drive.pdf",
      uploadedAt: "2026-06-17T09:00:00Z",
      verifiedAt: "2026-06-17T12:00:00Z",
    },
    contract: sig("Ewan MacRae", "2026-06-10T09:30:00Z", "seller-v1.0-2026-07"),
    status: "under-offer",
    createdAt: "2026-06-10T09:30:00Z",
  },
  // ---- Imported from the live mowatt.uk Hush Homes list (Phil's own
  // listings, anonymised exactly as published there). Seller: u-mowatt. ----
  {
    id: "h-mega-nb",
    sellerId: "u-mowatt",
    headline: "The MEGA Hush Hush: North Berwick has a secret",
    areaId: "east-lothian/north-berwick",
    addressLine: "Withheld · MEGA Hush Hush",
    price: 3000000,
    beds: 8,
    baths: 6,
    type: "detached",
    garden: true,
    features: ["parking", "garage", "sea-views", "period-features"],
    description:
      "A home we cannot name, describe or share publicly. What we can say is that it is extraordinary. A beautiful family home that could lend itself to shared or split ownership, for those dreaming of a luxury base in one of Scotland's most coveted golfing destinations. Total discretion; serious enquiries only.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "allied-surveyors", fileName: "home-report-mega-hush.pdf", verifiedAt: "2026-07-02T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-01T10:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "h-gullane-room",
    sellerId: "u-mowatt",
    headline: "Room to grow: Gullane family home with garden, gym and multiple reception spaces",
    areaId: "east-lothian/gullane",
    addressLine: "Withheld until viewing · Gullane",
    price: 790000,
    beds: 4,
    baths: 3,
    type: "detached",
    garden: true,
    features: ["parking", "garage", "new-build", "home-office"],
    description:
      "An immaculate four-bedroom detached newbuild (2020, approx. 2,400 sq ft) on a generous Gullane plot within walking distance of the beach, golf courses and village centre. Open-plan kitchen/dining/living with marble worktops and a bespoke media wall, two further reception rooms, and a converted double garage currently serving as a home gym. One of the development's largest rear gardens.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "allied-surveyors", fileName: "home-report-gullane-room-to-grow.pdf", verifiedAt: "2026-07-03T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-01T10:05:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "h-longniddry-4bed",
    sellerId: "u-mowatt",
    headline: "4 bed house at the end of a quiet Longniddry cul-de-sac",
    areaId: "east-lothian/longniddry",
    addressLine: "Withheld until viewing · Longniddry",
    price: 440000,
    beds: 4,
    baths: 2,
    type: "detached",
    garden: true,
    features: ["parking", "garage"],
    description:
      "A well-maintained, move-in-ready detached house in the original part of sought-after Longniddry: living room with fireplace, large dining kitchen with new patio doors to a south-facing garden, a downstairs double bedroom with upgraded shower room, and an integral garage. 111 m² (1,194 sq ft), with shops, the primary school, the station and the beach all within easy reach.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "graham-sibbald", fileName: "home-report-longniddry-4bed.pdf", verifiedAt: "2026-07-05T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-04T10:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "h-nb-seaview-flat",
    sellerId: "u-mowatt",
    headline: "3 bed flat with sea views, garage and shared garden in North Berwick",
    areaId: "east-lothian/north-berwick",
    addressLine: "Withheld until viewing · North Berwick High Street",
    price: 620000,
    beds: 3,
    baths: 1,
    type: "flat",
    garden: true,
    features: ["sea-views", "garage", "parking", "period-features"],
    description:
      "A characterful top-floor flat at the foot of North Berwick's High Street: three bedrooms, an L-shaped living room with wood-burning fire and dual sea-view windows, a sit-in kitchen and a cupola-lit hallway generous enough to live in. Private stairwell shared with one neighbour only; private garage, parking and shared garden complete the picture.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "allied-surveyors", fileName: "home-report-nb-seaview-flat.pdf", verifiedAt: "2026-07-08T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-07T10:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-07-08T10:00:00Z",
  },
  {
    id: "h-nb-flexible",
    sellerId: "u-mowatt",
    headline: "Large family home with flexible living arrangement in North Berwick",
    areaId: "east-lothian/north-berwick",
    addressLine: "Withheld until viewing · North Berwick",
    price: 1200000,
    beds: 5,
    baths: 3,
    type: "detached",
    garden: true,
    features: ["parking", "garage", "home-office"],
    description:
      "A substantial detached family home offering five to six bedrooms, three bathrooms and 3,355 sq ft over two floors. A generous open-plan kitchen, dining and living space with four zones and a wood-burning stove forms the heart of the home; an over-garage room offers strong studio or annexe potential. Beautifully landscaped gardens, patio areas and a private gravel driveway. The owners are looking to complete in Spring 2027.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "graham-sibbald", fileName: "home-report-nb-flexible.pdf", verifiedAt: "2026-07-10T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-09T10:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "h-longniddry-annexe",
    sellerId: "u-mowatt",
    headline: "A future-proof Longniddry home plus self-contained annexe",
    areaId: "east-lothian/longniddry",
    addressLine: "Withheld until viewing · Longniddry",
    price: 750000,
    beds: 5,
    baths: 3,
    type: "detached",
    garden: true,
    features: ["parking", "new-build", "home-office"],
    description:
      "A contemporary detached four-bedroom home with a one-bed self-contained annexe, minutes from the beach and a quick commute to Edinburgh. Double-height open-plan kitchen, dining and family room with bifold doors to a sun-trap courtyard terrace; German kitchen with granite worktops. The two-storey annexe has its own entrance, terrace and driveway, ideal for guests, multi-generational living or holiday letting.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "allied-surveyors", fileName: "home-report-longniddry-annexe.pdf", verifiedAt: "2026-07-12T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-11T10:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-07-12T10:00:00Z",
  },
  {
    id: "h-meadows-townhouse",
    sellerId: "u-mowatt",
    headline: "Exceptional three-storey Meadows townhouse undergoing luxury refurbishment",
    areaId: "edinburgh/marchmont",
    addressLine: "Withheld until viewing · beside the Meadows",
    price: 1535000,
    beds: 4,
    baths: 4,
    type: "townhouse",
    garden: true,
    features: ["period-features", "home-office"],
    description:
      "Part of a phased redevelopment of a beautiful terrace of eight historic hospital buildings beside the Meadows: a substantial 4/5 bedroom townhouse (plus study) over three storeys, 2,485 sq ft, undergoing a full high-quality refurbishment due for completion in August 2026. Riddle & Coghill kitchen, new sash-and-case windows, air-source heating and newly landscaped gardens with lane access. Fixed price; only available through the Matchlist.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "graham-sibbald", fileName: "home-report-meadows-townhouse.pdf", verifiedAt: "2026-07-14T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-13T10:00:00Z", "seller-v1.0-2026-07"),
    status: "live",
    createdAt: "2026-07-14T10:00:00Z",
  },
  {
    id: "h-nb-bungalow",
    sellerId: "u-mowatt",
    headline: "2 bed bungalow with planning to extend in North Berwick",
    areaId: "east-lothian/north-berwick",
    addressLine: "Withheld until viewing · North Berwick",
    price: 480000,
    beds: 2,
    baths: 1,
    type: "bungalow",
    garden: true,
    features: ["parking"],
    description:
      "A charming chalet bungalow quietly positioned at the foot of a cul-de-sac in one of North Berwick's most coveted corners, with the Lodge Gardens on the doorstep. Two generous double bedrooms, a large sitting room with feature fireplace, a sunny garden room and fully enclosed gardens, plus full planning permission for a significant extension. Under offer to a registered Quiet Seeker.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "verified", supplier: "allied-surveyors", fileName: "home-report-nb-bungalow.pdf", verifiedAt: "2026-07-06T09:00:00Z" },
    contract: sig("Mowatt Client", "2026-07-05T10:00:00Z", "seller-v1.0-2026-07"),
    status: "under-offer",
    createdAt: "2026-07-06T10:00:00Z",
  },
  {
    // One click from live: report uploaded, awaiting admin verification.
    // Verifying it demos the "possible match" alerts — it scores 90%+ for
    // Ailsa (QS-2104) and Sandy (QS-2210).
    id: "h-aberlady",
    sellerId: "u-tam",
    headline: "Sunlit detached family home by Aberlady Bay",
    areaId: "east-lothian/aberlady",
    addressLine: "4 Craigielaw Road, Aberlady",
    price: 795000,
    beds: 4,
    baths: 2,
    type: "detached",
    garden: true,
    features: ["parking", "sea-views", "garage"],
    description:
      "A bright detached family home on the edge of Aberlady with the nature reserve at the foot of the road, a west-facing garden and views over the bay.",
    photos: [],
    floorPlan: null,
    homeReport: {
      status: "uploaded",
      supplier: "allied-surveyors",
      orderedAt: "2026-07-21T09:00:00Z",
      invoiceId: "inv-hr-aberlady",
      fileName: "home-report-4-craigielaw-road.pdf",
      uploadedAt: "2026-07-24T09:00:00Z",
    },
    contract: sig("Tam Buchanan", "2026-07-20T10:30:00Z", "seller-v1.0-2026-07"),
    status: "pending-approval",
    createdAt: "2026-07-20T10:30:00Z",
  },
  {
    id: "h-morningside",
    sellerId: "u-struan",
    headline: "Victorian terrace near the Hermitage",
    areaId: "edinburgh/morningside",
    addressLine: "31 Cluny Gardens, Morningside",
    price: 620000,
    beds: 4,
    baths: 2,
    type: "terraced",
    garden: true,
    features: ["period-features", "home-office"],
    description:
      "A double-fronted Victorian terrace with the Hermitage of Braid at the end of the road. Draft listing; Home Report still to be ordered.",
    photos: [],
    floorPlan: null,
    homeReport: { status: "none" },
    contract: sig("Struan Kerr", "2026-07-10T10:20:00Z", "seller-v1.0-2026-07"),
    status: "draft",
    // Struan ticked "I'll do the Home Report later" — preview listing.
    previewListed: true,
    createdAt: "2026-07-10T10:20:00Z",
  },
  {
    id: "h-inverness",
    sellerId: "u-isla",
    headline: "New-build townhouse by the Ness Islands",
    areaId: "highland/inverness",
    addressLine: "9 Island Bank Lane, Inverness",
    price: 315000,
    beds: 4,
    baths: 3,
    type: "townhouse",
    garden: true,
    features: ["new-build", "parking", "home-office"],
    description:
      "A three-storey townhouse finished last year, with the river path to the Ness Islands at the door and an NHBC warranty still warm.",
    photos: [],
    floorPlan: null,
    homeReport: {
      status: "uploaded",
      supplier: "graham-sibbald",
      orderedAt: "2026-07-08T09:00:00Z",
      invoiceId: "inv-hr-inverness",
      fileName: "home-report-9-island-bank-lane.pdf",
      uploadedAt: "2026-07-15T09:00:00Z",
    },
    contract: sig("Isla Farquhar", "2026-07-07T15:00:00Z", "seller-v1.0-2026-07"),
    status: "pending-approval",
    createdAt: "2026-07-07T15:00:00Z",
  },
  {
    id: "h-melrose",
    sellerId: "u-morag",
    headline: "Stone cottage under the Eildons",
    areaId: "scottish-borders/melrose",
    addressLine: "Eildon View, Dingleton Road, Melrose",
    price: 410000,
    beds: 3,
    baths: 2,
    type: "cottage",
    garden: true,
    features: ["rural", "period-features"],
    description:
      "Thick stone walls, a cottage garden that hums in June, and the Eildon Hills filling every back window. Sold via Matchlisted, June 2026.",
    photos: [],
    floorPlan: null,
    homeReport: {
      status: "verified",
      supplier: "allied-surveyors",
      orderedAt: "2026-05-22T09:00:00Z",
      invoiceId: "inv-hr-melrose",
      fileName: "home-report-eildon-view.pdf",
      uploadedAt: "2026-05-28T09:00:00Z",
      verifiedAt: "2026-05-28T12:00:00Z",
    },
    contract: sig("Morag Sinclair", "2026-05-21T10:00:00Z", "seller-v1.0-2026-07"),
    status: "sold",
    createdAt: "2026-05-21T10:00:00Z",
  },
];

export const sampleLawyers: Lawyer[] = [
  {
    id: "law-thorntons",
    firm: "Thorntons Law LLP",
    contactName: "Susan Geddes",
    location: "Edinburgh & Dundee",
    feeEstimate: 1350,
    blurb: "Full-service Scottish firm; purchase conveyancing across the country with fixed-fee quotes.",
  },
  {
    id: "law-aberdein",
    firm: "Aberdein Considine",
    contactName: "Mark Provan",
    location: "Aberdeen, Glasgow & Edinburgh",
    feeEstimate: 1250,
    blurb: "High-volume residential team with offices in every major city.",
  },
  {
    id: "law-lindsays",
    firm: "Lindsays",
    contactName: "Catriona Hay",
    location: "Edinburgh, Glasgow & Dundee",
    feeEstimate: 1450,
    blurb: "Long-established firm, strong on period property and rural title questions.",
  },
  {
    id: "law-macleod",
    firm: "Macleod & MacCallum",
    contactName: "Iain Fraser",
    location: "Inverness & the Highlands",
    feeEstimate: 1150,
    blurb: "The Highland specialists: crofts, new builds and everything between.",
  },
];

export const sampleSlots: ViewingSlot[] = [
  { id: "slot-g1", homeId: "h-gullane", start: "2026-07-21T17:30:00Z", end: "2026-07-21T18:00:00Z", bookedBy: null },
  { id: "slot-g2", homeId: "h-gullane", start: "2026-07-22T12:00:00Z", end: "2026-07-22T12:30:00Z", bookedBy: null },
  { id: "slot-g3", homeId: "h-gullane", start: "2026-07-25T10:00:00Z", end: "2026-07-25T10:30:00Z", bookedBy: null },
  { id: "slot-s1", homeId: "h-stockbridge", start: "2026-07-20T17:00:00Z", end: "2026-07-20T17:30:00Z", bookedBy: null },
  { id: "slot-s2", homeId: "h-stockbridge", start: "2026-07-23T18:00:00Z", end: "2026-07-23T18:30:00Z", bookedBy: null },
  { id: "slot-l1", homeId: "h-largs", start: "2026-07-24T14:00:00Z", end: "2026-07-24T14:30:00Z", bookedBy: null },
  { id: "slot-t1", homeId: "h-troon", start: "2026-06-24T17:00:00Z", end: "2026-06-24T17:30:00Z", bookedBy: "u-kirsty" },
];

export const sampleViewings: Viewing[] = [
  {
    id: "view-troon-kirsty",
    homeId: "h-troon",
    seekerId: "u-kirsty",
    slotId: "slot-t1",
    start: "2026-06-24T17:00:00Z",
    end: "2026-06-24T17:30:00Z",
    status: "completed",
    feedback: "Loved the light and the level access. Garage seals it.",
    stillInterested: true,
  },
];

export const sampleOffers: Offer[] = [
  {
    id: "offer-troon",
    homeId: "h-troon",
    seekerId: "u-kirsty",
    lawyerId: "law-aberdein",
    amount: 342000,
    note: "Entry ideally late September.",
    status: "accepted",
    history: [
      { at: "2026-06-26T10:00:00Z", event: "Offer submitted: £342,000" },
      { at: "2026-06-27T09:30:00Z", event: "Accepted by the seller" },
    ],
    createdAt: "2026-06-26T10:00:00Z",
  },
  {
    id: "offer-melrose",
    homeId: "h-melrose",
    seekerId: "u-fenella",
    lawyerId: "law-thorntons",
    amount: 405000,
    status: "accepted",
    history: [
      { at: "2026-06-02T11:00:00Z", event: "Offer submitted: £405,000" },
      { at: "2026-06-03T09:00:00Z", event: "Accepted by the seller" },
      { at: "2026-06-30T12:00:00Z", event: "Missives concluded" },
    ],
    createdAt: "2026-06-02T11:00:00Z",
    missivesConcludedAt: "2026-06-30T12:00:00Z",
  },
];

export const sampleInvoices: Invoice[] = [
  { id: "inv-hr-gullane", userId: "u-gordon", homeId: "h-gullane", kind: "home-report", description: "Home Report · Allied Surveyors (14 Marine Terrace)", net: 625, vat: 125, status: "paid", createdAt: "2026-06-13T09:00:00Z", paidAt: "2026-06-13T09:02:00Z" },
  { id: "inv-hr-shawlands", userId: "u-rachel", homeId: "h-shawlands", kind: "home-report", description: "Home Report · Graham + Sibbald (48 Kilmarnock Road)", net: 550, vat: 110, status: "paid", createdAt: "2026-06-16T09:00:00Z", paidAt: "2026-06-16T09:01:00Z" },
  { id: "inv-hr-largs", userId: "u-morag", homeId: "h-largs", kind: "home-report", description: "Home Report · Allied Surveyors (5 Broomfields Promenade)", net: 545, vat: 109, status: "paid", createdAt: "2026-06-06T09:00:00Z", paidAt: "2026-06-06T09:05:00Z" },
  { id: "inv-hr-stockbridge", userId: "u-ewan", homeId: "h-stockbridge", kind: "home-report", description: "Home Report · Graham + Sibbald (7A Dean Terrace)", net: 595, vat: 119, status: "paid", createdAt: "2026-06-09T09:00:00Z", paidAt: "2026-06-09T09:03:00Z" },
  { id: "inv-hr-standrews", userId: "u-morag", homeId: "h-standrews", kind: "home-report", description: "Home Report · Allied Surveyors (3 Gibson Place)", net: 610, vat: 122, status: "paid", createdAt: "2026-06-20T09:00:00Z", paidAt: "2026-06-20T09:02:00Z" },
  { id: "inv-hr-dunkeld", userId: "u-isla", homeId: "h-dunkeld", kind: "home-report", description: "Home Report · Graham + Sibbald (Larch Cottage)", net: 570, vat: 114, status: "paid", createdAt: "2026-06-21T09:00:00Z", paidAt: "2026-06-21T09:04:00Z" },
  { id: "inv-hr-troon", userId: "u-ewan", homeId: "h-troon", kind: "home-report", description: "Home Report · Allied Surveyors (22 Bentinck Drive)", net: 555, vat: 111, status: "paid", createdAt: "2026-06-11T09:00:00Z", paidAt: "2026-06-11T09:01:00Z" },
  { id: "inv-hr-aberlady", userId: "u-tam", homeId: "h-aberlady", kind: "home-report", description: "Home Report · Allied Surveyors (4 Craigielaw Road)", net: 555, vat: 111, status: "paid", createdAt: "2026-07-21T09:00:00Z", paidAt: "2026-07-21T09:02:00Z" },
  { id: "inv-hr-inverness", userId: "u-isla", homeId: "h-inverness", kind: "home-report", description: "Home Report · Graham + Sibbald (9 Island Bank Lane)", net: 560, vat: 112, status: "paid", createdAt: "2026-07-08T09:00:00Z", paidAt: "2026-07-08T09:02:00Z" },
  { id: "inv-hr-melrose", userId: "u-morag", homeId: "h-melrose", kind: "home-report", description: "Home Report · Allied Surveyors (Eildon View)", net: 585, vat: 117, status: "paid", createdAt: "2026-05-22T09:00:00Z", paidAt: "2026-05-22T09:01:00Z" },
  { id: "inv-dep-kirsty", userId: "u-kirsty", homeId: "h-troon", offerId: "offer-troon", kind: "conveyancing-deposit", description: "Conveyancing deposit · Aberdein Considine appointed", net: 100, vat: 20, status: "paid", createdAt: "2026-06-25T15:00:00Z", paidAt: "2026-06-25T15:01:00Z" },
  { id: "inv-dep-fenella", userId: "u-fenella", homeId: "h-melrose", offerId: "offer-melrose", kind: "conveyancing-deposit", description: "Conveyancing deposit · Thorntons Law appointed", net: 100, vat: 20, status: "paid", createdAt: "2026-06-01T10:00:00Z", paidAt: "2026-06-01T10:01:00Z" },
  { id: "inv-fee-fenella", userId: "u-fenella", homeId: "h-melrose", offerId: "offer-melrose", kind: "sourcing-fee", description: "Buyer fee · fixed £300 + VAT (Eildon View, missives concluded 30 Jun 2026)", net: 300, vat: 60, status: "due", createdAt: "2026-06-30T12:05:00Z" },
];

export const sampleSaved: SavedHome[] = [
  { seekerId: "u-ailsa", homeId: "h-gullane", savedAt: "2026-07-12T09:00:00Z" },
  { seekerId: "u-freya", homeId: "h-stockbridge", savedAt: "2026-07-10T18:00:00Z" },
];

export const sampleNotifications: AppNotification[] = [
  {
    id: "n-ailsa-1",
    userId: "u-ailsa",
    kind: "match",
    title: "It's a match: 99%",
    body: "A Hush Home in Gullane matches your brief almost perfectly. This could be the one.",
    href: "/homes/h-gullane",
    createdAt: "2026-07-11T08:00:00Z",
    readAt: null,
  },
  {
    id: "n-gordon-1",
    userId: "u-gordon",
    kind: "match",
    title: "It's a match: 99%",
    body: "A registered Quiet Seeker (cash buyer, nothing to sell) is a 99% match with your Hush Home.",
    href: "/dashboard",
    createdAt: "2026-07-11T08:00:00Z",
    readAt: null,
  },
  {
    id: "n-kirsty-1",
    userId: "u-kirsty",
    kind: "offer",
    title: "Offer accepted",
    body: "Your offer of £342,000 on the Troon bungalow was accepted. Aberdein Considine will take it from here.",
    href: "/dashboard",
    createdAt: "2026-06-27T09:31:00Z",
    readAt: "2026-06-27T10:00:00Z",
  },
];
