// Demo environment for the product video (docs/DEMO-VIDEO.md §0, rule 2).
//
//   node scripts/demo/demo-env.mjs write          -> .env.demo from the local Supabase stack
//   node scripts/demo/demo-env.mjs run -- <cmd>   -> run <cmd> with .env.demo applied
//
// `.env.local` is never read or written. Next.js does not overwrite a variable
// that is already set in the process environment (even to ""), so every key
// the app reads is set here explicitly, and the ones that reach real services
// (Stripe, Resend) are set to empty. Refuses to run unless both the API and
// the database are on 127.0.0.1.

import { execSync, spawn } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "../..");
const ENV_FILE = resolve(ROOT, ".env.demo");
const LOCAL = /^(https?|postgres(ql)?):\/\/([^@/]*@)?127\.0\.0\.1[:/]/;

function localStatus() {
  const out = execSync("npx supabase status -o env", { cwd: ROOT, encoding: "utf8" });
  const vars = {};
  for (const line of out.split(/\r?\n/)) {
    const m = line.match(/^([A-Z_]+)="?(.*?)"?$/);
    if (m) vars[m[1]] = m[2];
  }
  return vars;
}

function parseEnv(text) {
  const vars = {};
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) vars[m[1]] = m[2];
  }
  return vars;
}

function assertLocal(env) {
  for (const key of ["NEXT_PUBLIC_SUPABASE_URL", "DATABASE_URL"]) {
    if (!LOCAL.test(env[key] ?? "")) {
      console.error(`Refusing: ${key} is not on 127.0.0.1 (${env[key] || "unset"}).`);
      process.exit(1);
    }
  }
}

function write() {
  const s = localStatus();
  const env = {
    MATCHLISTED_DEMO: "1",
    NEXT_PUBLIC_SUPABASE_URL: s.API_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: s.PUBLISHABLE_KEY || s.ANON_KEY,
    SUPABASE_SECRET_KEY: s.SECRET_KEY || s.SERVICE_ROLE_KEY,
    DATABASE_URL: s.DB_URL,
    NEXT_PUBLIC_SITE_URL: "http://localhost:3000",
    // Real services stay off for the demo: no card processing, no email.
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "",
    STRIPE_SECRET_KEY: "",
    STRIPE_WEBHOOK_SECRET: "",
    RESEND_API_KEY: "",
    EMAIL_FROM: "demo@example.com",
    EMAIL_ADMIN: "demo-admin@example.com",
  };
  assertLocal(env);
  const body =
    "# Generated by scripts/demo/demo-env.mjs from the LOCAL Supabase stack.\n" +
    "# Local development keys only. Gitignored by .env*.\n" +
    Object.entries(env).map(([k, v]) => `${k}=${v}`).join("\n") + "\n";
  writeFileSync(ENV_FILE, body);
  console.log(`Wrote .env.demo. Supabase URL: ${env.NEXT_PUBLIC_SUPABASE_URL}`);
}

function run(cmd) {
  if (!existsSync(ENV_FILE)) {
    console.error("No .env.demo. Run: node scripts/demo/demo-env.mjs write");
    process.exit(1);
  }
  const env = parseEnv(readFileSync(ENV_FILE, "utf8"));
  assertLocal(env);
  console.log(`\n  DEMO DATABASE  ${env.NEXT_PUBLIC_SUPABASE_URL}  (local, not the hosted project)\n`);
  const child = spawn(cmd.join(" "), { cwd: ROOT, stdio: "inherit", shell: true, env: { ...process.env, ...env } });
  child.on("exit", (code) => process.exit(code ?? 1));
}

const [mode, ...rest] = process.argv.slice(2);
if (mode === "write") write();
else if (mode === "run" && rest[0] === "--" && rest.length > 1) run(rest.slice(1));
else {
  console.error("Usage: demo-env.mjs write | run -- <command>");
  process.exit(1);
}
